name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@main

    - name: Install Pandoc dependency
      uses: nikeee/setup-pandoc@v1

    - name: Create folder
      run: mkdir .tmp

    - name: Make prod
      run: make PROD=1

