name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Pandoc dependency
      uses: docker://pandoc/core:2.9

    - name: Checkout
      uses: actions/checkout@v4

    - name: Create folder
      run: mkdir .tmp

    - name: Make prod
      run: make PROD=1

